[package]
name = "stamps_test"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0.140"
tokio = { version = "1", features = ["full"] }
